### ISSUE TITLE
Selectable shelf

### ISSUE THREAD

**Issue by dmillot** [NicolasBrondin/scribee#1]
A couple of times, the shelf is selectable and it's impossible to deselect it. I have the option of putting it in one of the cells.

**User-Agent :** Mozilla/5.0 (Windows NT 10.0; …) Gecko/20100101 Firefox/75.0

![bug](https://user-images.githubusercontent.com/47076692/81399806-fcda2f00-912b-11ea-88f2-aec03055cf1c.png)

![bug2](https://user-images.githubusercontent.com/47076692/81399836-10859580-912c-11ea-8e97-ac5d728d6a96.png)

Maybe console errors can help :

![bug3](https://user-images.githubusercontent.com/47076692/81399906-3743cc00-912c-11ea-84e1-8e3427cdb64a.png)

By the way, there's a lot of console log !
Hope this helps.

**Comment by NicolasBrondin** [comment]
Thanks, I will fix this as soon as I can and I'll remove the logs at the same time 😄
